### ISSUE TITLE
Cache permissions issue

### ISSUE THREAD

**Issue by pstephenson02** [capistrano/symfony#38]
Hi! I am working on setting up Capistrano for a Symfony project and I've run into a strange permissions issue and I hope someone can point me in the right direction...

The deployments are successful, however, when I attempt to access the page, the web server logs are showing me a permissions error:

```bash
[Thu Jun 18 12:49:14.785114 2015] [:error] [pid 19090] [client 172.20.0.171:35065] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to write cache file "/var/www/cdpaccess/releases/20150618174628/app/cache/cdp/prod/classes.php".' in /var/www/cdpaccess/shared/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:205\nStack trace:\n#0 /var/www/cdpaccess/shared/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(122): Symfony\\Component\\ClassLoader\\ClassCollectionLoader::writeCacheFile('/var/www/cdpacc...', '<?php  ????name...')\n#1 /var/www/cdpaccess/releases/20150618174628/app/bootstrap.php.cache(758): Symfony\\Component\\ClassLoader\\ClassCollectionLoader::load(Array, '/var/www/cdpacc...', 'classes', false, false, '.php')\n#2 /var/www/cdpaccess/releases/20150618174628/web/app.php(20): Symfony\\Component\\HttpKernel\\Kernel->loadClassCache()\n#3 {main}\n  thrown in /var/www/cdpaccess/shared/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php on line 205
```

Here is some information that should help:

[Here is a gist of the deployment](https://gist.github.com/pstephenson02/9ee230dd6b6f8f7915d4)

Gems:

```bash
*** LOCAL GEMS ***

bundler (1.10.4)
capistrano (3.4.0)
capistrano-composer (0.0.6)
capistrano-file-permissions (0.1.1)
capistrano-symfony (0.4.0)
colorize (0.7.7)
i18n (0.7.0)
net-scp (1.2.1)
net-ssh (2.9.2)
rake (10.4.2)
sshkit (1.7.1)
```

deploy.rb:

```bash
lock '3.4.0'

set :application, 'cdpaccess'
set :repo_url, 'git@github.com:InternationalCodeCouncil/cdpaccess.git'
set :deploy_to, '/var/www/html/cdpaccess'

# Default value for :linked_files is []
set :linked_files, fetch(:linked_files, []).push('app/config/parameters.yml', 'src/Caxy/AvectraBundle/Resources/config/parameters.yml')

# Default value for linked_dirs is []
set :linked_dirs, fetch(:linked_dirs, []).push('vendor')

# Install composer
SSHKit.config.command_map[:composer] = "php #{shared_path.join("composer.phar")}"
set :composer_install_flags, '--no-interaction --optimize-autoloader'
after 'deploy:starting', 'composer:install_executable'

# Dump js routes
before 'deploy:updated', 'deploy:dump_js_routes'

# Set Symfony permissions
set :webserver_user, "apache"
set :permission_method, :acl
set :use_set_permissions, true
set :file_permissions_paths, [fetch(:log_path), fetch(:cache_path), "app/var", "web/uploads"]

# Install assets
before 'deploy:updated', 'symfony:assets:install'
before 'deploy:updated', 'symfony:assetic:dump'

namespace :deploy do
  after :restart, :clear_cache do
    on roles(:web), in: :groups, limit: 3, wait: 10 do
      # Here we can do anything such as:
      # within release_path do
      #   execute :rake, 'cache:clear'
      # end
    end
  end

  task :dump_js_routes do
    invoke 'symfony:console', 'bazinga:expose-translation:dump', 'web/translations'
  end
end
```

All of the tasks seem to be running. I logged into the server and checked permissions on the offending folders - it looks like the setfacl command was executed:

```bash
[cdpaccess@cdp-qa app]$ ls -l
total 120
-rw-rw-r--  1 cdpaccess cdpaccess   141 Jun 18 12:40 AppCache.php
-rwxrwxr-x  1 cdpaccess cdpaccess  6716 Jun 18 12:40 AppKernel.php
-rw-rw-r--  1 cdpaccess cdpaccess   487 Jun 18 12:40 Application.php
-rw-rw-r--  1 cdpaccess cdpaccess   474 Jun 18 12:40 autoload.php
-rw-rw-r--  1 cdpaccess cdpaccess 48879 Jun 18 12:54 bootstrap.php.cache
drwxrwxr-x+ 3 cdpaccess cdpaccess    16 Jun 18 12:54 cache
-rw-rw-r--  1 cdpaccess cdpaccess  1643 Jun 18 12:54 check.php
drwxrwxr-x  4 cdpaccess cdpaccess  4096 Jun 18 12:54 config
-rwxrwxr-x  1 cdpaccess cdpaccess   918 Jun 18 12:40 console
drwxrwxr-x  4 cdpaccess cdpaccess    30 Jun 18 12:40 DoctrineMigrations
lrwxrwxrwx  1 cdpaccess cdpaccess    34 Jun 18 12:54 logs -> /var/www/cdpaccess/shared/app/logs
drwxrwxr-x  2 cdpaccess cdpaccess    29 Jun 18 12:40 PHPUnit
-rw-rw-r--  1 cdpaccess cdpaccess  2234 Jun 18 12:40 phpunit.xml.dist
drwxrwxr-x  7 cdpaccess cdpaccess    77 Jun 18 12:40 Resources
-rw-rw-r--  1 cdpaccess cdpaccess 26577 Jun 18 12:54 SymfonyRequirements.php
drwxrwxr-x+ 3 cdpaccess cdpaccess    31 Jun 18 12:54 var
```

If I run the setfacl commands 1 last time after the deployment has been complete, it works and I can access the site.

I've used capistrano successfully on other Symfony projects (although I have had issues with permissions), but I'm kind of stuck here. Any advice, workarounds, etc would be appreciated. I'm not a ruby developer so bear with me!

Thanks in advance.

**Comment by pstephenson02** [comment]
Ok, some more information here.
While setfacl is honestly a bit of voodoo to me, it does appear that despite adding the flag:

```bash
set :webserver_user, "apache"
```
in my deploy.rb, the setfacl command run does not include web server user in the command:

```bash
INFO [041334b0] Running /usr/bin/env setfacl -Rm u:cdpaccess:rwx /var/www/cdpaccess/shared/app/logs /var/www/cdpaccess/releases/20150618175416/app/cache /var/www/cdpaccess/releases/20150618175416/app/var /var/www/cdpaccess/shared/web/uploads as cdpaccess@cdp-qa.caxy.com
DEBUG [041334b0] Command: ( SYMFONY_ENV=prod /usr/bin/env setfacl -Rm u:cdpaccess:rwx /var/www/cdpaccess/shared/app/logs /var/www/cdpaccess/releases/20150618175416/app/cache /var/www/cdpaccess/releases/20150618175416/app/var /var/www/cdpaccess/shared/web/uploads )
INFO [041334b0] Finished in 0.091 seconds with exit status 0 (successful).
INFO [fdc1520e] Running /usr/bin/env setfacl -Rdm u:cdpaccess:rwx /var/www/cdpaccess/shared/app/logs /var/www/cdpaccess/releases/20150618175416/app/cache /var/www/cdpaccess/releases/20150618175416/app/var /var/www/cdpaccess/shared/web/uploads as cdpaccess@cdp-qa.caxy.com
DEBUG [fdc1520e] Command: ( SYMFONY_ENV=prod /usr/bin/env setfacl -Rdm u:cdpaccess:rwx /var/www/cdpaccess/shared/app/logs /var/www/cdpaccess/releases/20150618175416/app/cache /var/www/cdpaccess/releases/20150618175416/app/var /var/www/cdpaccess/shared/web/uploads )
INFO [fdc1520e] Finished in 0.090 seconds with exit status 0 (successful).
```

If I run the same commands again, but I include the web server user:

```bash
setfacl -Rm u:cdpaccess:rwx -m u:apache:rwx ...
setfacl -Rdm u:cdpaccess:rwx -m u:apache:rwx ...
```

This works!

**Comment by pstephenson02** [comment]
Last comment for anyone reading:

I was able to resolve this by adding the line:

```bash
set :file_permissions_users, ['apache']
```

This comes from the [capistrano/file-permissions documentation](https://github.com/capistrano/file-permissions#usage) and after adding it indeed I can see the u:apache:rwx is added to the setfacl command. 

I'm unsure as to whether this set :webserver_user is intended to accomplish the same thing or not. Either way, hope this helps someone!

Thanks

**Comment by wideawake** [comment]
many thanks @pstephenson02  

I created a PR.
