### ISSUE TITLE
Doctrine migrations task freezes deploy

### ISSUE THREAD

**Issue by webdevilopers** [capistrano/symfony#53]
My migration command:
```
SYMFONY_ENV=prod /usr/bin/env php app/console doctrine:migrations:migrate --verbose --no-debug
```

The task:
```ruby
namespace :tasks do
  task :migrate do
    invoke 'symfony:console', 'doctrine:migrations:migrate', '--verbose'
  end
end

namespace :deploy do
  after :updated, 'tasks:migrate'
end
```

The interaction starts and asks me if I want to migrate. Wheter I choose Y or N the cap deploy will freeze.
This normally indicates there is an error inside the migrations files.

I logged in to the server with the same SSH user and run the command manually with success.
In my case all migrations already were migrated:
```                                                              
WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)y
No migrations to execute.
```

I know there are some issues with Capistrano and @FreeBSD. For instance I had to change the default bash to be able to export the SYMFONY_ENV:
https://github.com/capistrano/symfony/issues/24#issuecomment-181342031

Any idea why the process is freezing? I run the cap deploy with `--trace` and the migrations with `--verbose` but no feedback.

Nothing inside the error logs. After cancelling:
```
^Ccap aborted!
Interrupt: 
/var/lib/gems/1.9.1/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:20:in `join'
/var/lib/gems/1.9.1/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:20:in `map'
/var/lib/gems/1.9.1/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:20:in `execute'
/var/lib/gems/1.9.1/gems/sshkit-1.7.1/lib/sshkit/coordinator.rb:15:in `each'
/var/lib/gems/1.9.1/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:55:in `on'
/var/lib/gems/1.9.1/gems/capistrano-symfony-0.4.0/lib/capistrano/tasks/symfony.rake:12:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:16:in `invoke'
app/config/deploy.rb:60:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/capistrano-3.4.0/lib/capistrano/dsl/task_enhancements.rb:14:in `block in after'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:16:in `invoke'
/var/lib/gems/1.9.1/gems/capistrano-3.4.0/lib/capistrano/tasks/framework.rake:65:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/capistrano-3.4.0/lib/capistrano/tasks/framework.rake:61:in `each'
/var/lib/gems/1.9.1/gems/capistrano-3.4.0/lib/capistrano/tasks/framework.rake:61:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:in `run'
/var/lib/gems/1.9.1/gems/capistrano-3.4.0/bin/cap:3:in `<top (required)>'
/usr/local/bin/cap:23:in `load'
/usr/local/bin/cap:23:in `<main>'
Tasks: TOP => symfony:console
The deploy has failed with an error: 
** Invoke deploy:failed (first_time)
** Execute deploy:failed
```

**Comment by peterjmit** [comment]
@webdevilopers I think this is more an issue for SSHKit and/or Capistrano itself. In Capistrano v2 I believe you had to set `pty: true` to get an interactive prompt, but I'm not sure if that rolled over into v3 & ssh kit.

Personally I run with the `--no-interaction` flag to avoid such issues (as deploys are automated).

**Comment by webdevilopers** [comment]
Thanks @peterjmit . I switched to `--no-interaction` and it seems to work fine now:

```ruby
namespace :tasks do
  task :migrate do
    invoke 'symfony:console', 'doctrine:migrations:migrate', '--no-interaction --verbose'
  end
end
```

Have you ever tried this gem by @kilhage ?
https://github.com/glooby/capistrano-symfony-doctrine

**Comment by peterjmit** [comment]
@webdevilopers I haven't no, but looks handy!
